### ISSUE TITLE
[BUG] 피플 목록 조회시 500 Internal Server Error

### ISSUE THREAD

**Issue by toothlessdev** [Principes-Artis-Mechanicae/get-p-server#146]
## **📝 설명**
피플 목록 조회시 500 에러가 발생합니다

## **❎ 재현 단계**

1. https://beta-get-p.netlify.app/ 에 접속합니다
2. 브라우저 네트워크 탭을 엽니다
3. 피플 목록 조회에 대해 500 에러가 발생합니다

|프로퍼티|값|
|--|--|
|URL|https://api.principes.xyz/get-p/v2/people|
|METHOD|POST|
|QUERY|?page=0&size=10&sort=peopleId,desc|

```json
{
    "status": 500,
    "errors": [
        {
            "code": "INTERNAL_SERVER_ERROR",
            "message": "서버 내부 오류가 발생했습니다."
        }
    ]
}
```

## **✅ 예상 결과**
피플 목록 조회 API 가 200 응답을 반환합니다

## **🔗 첨부파일**
<img width="701" alt="image" src="https://github.com/user-attachments/assets/cb4d385b-049b-4d74-890c-c70e997063cd">

<img width="623" alt="image" src="https://github.com/user-attachments/assets/4ff42479-db21-4521-bf2c-85aa3fedd9a4">

**Comment by wlgns12370** [comment]
혹시 피플 목록 조회가 `GET`메서드로 알고 있는데 `api`명세서에는 `POST`로 되어있나요??
`GET`으로 한번 시도해줄 수 있을까요?

**Comment by scv1702** [comment]
확인해보니 개발 서버의 데이터베이스 DDL이 현재 JPA 매핑과 맞지 않아 발생했던 오류였네요. 데이터베이스 마이그레이션 도구를 사용해서 한 번 고쳐보겠습니다.

**Comment by scv1702** [comment]
개발 서버의 데이터베이스 테이블을 모두 재생성한 뒤 데이터를 복구하여 해당 이슈를 해결했습니다.
